#!/usr/bin/env python3
"""
Generate type stubs for ucon.constants from runtime introspection.

This script imports ucon.constants and generates a .pyi stub file by:
1. Extracting all Constant objects loaded from the TOML
2. Including the Constant class signature
3. Including enumeration functions and alias accessors
4. Including Unicode and ASCII aliases from __all__

Usage:
    python scripts/generate_constant_stubs.py > ucon/constants.pyi
    python scripts/generate_constant_stubs.py --check  # Verify stub is current
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure we import from the local package
sys.path.insert(0, str(Path(__file__).parent.parent))

from ucon.constants import Constant, __all__ as CONST_ALL
from ucon.constants import _get_constants


HEADER = '''\
# Auto-generated type stubs for ucon.constants
# Generated by: scripts/generate_constant_stubs.py
# Regenerate with: make stubs
# DO NOT EDIT MANUALLY

from typing import Union

from ucon.core import Number, Unit, UnitProduct
from ucon.dimension import Dimension

'''


def generate_constant_class() -> list[str]:
    """Generate the Constant class stub."""
    lines = []
    lines.append("class Constant:")
    lines.append('    """A physical constant with CODATA uncertainty."""')
    lines.append("")
    lines.append("    symbol: str")
    lines.append("    name: str")
    lines.append("    value: float")
    lines.append("    unit: Union[Unit, UnitProduct]")
    lines.append("    uncertainty: Union[float, None]")
    lines.append('    source: str = "CODATA 2022"')
    lines.append('    category: str = "measured"')
    lines.append("    aliases: tuple = ()")
    lines.append("")
    lines.append("    def as_number(self) -> Number: ...")
    lines.append("")
    lines.append("    @property")
    lines.append("    def dimension(self) -> Dimension: ...")
    lines.append("    @property")
    lines.append("    def is_exact(self) -> bool: ...")
    lines.append("")
    lines.append("    def __mul__(self, other: object) -> Number: ...")
    lines.append("    def __rmul__(self, other: object) -> Number: ...")
    lines.append("    def __truediv__(self, other: object) -> Number: ...")
    lines.append("    def __rtruediv__(self, other: object) -> Number: ...")
    lines.append("    def __add__(self, other: object) -> Number: ...")
    lines.append("    def __radd__(self, other: object) -> Number: ...")
    lines.append("    def __sub__(self, other: object) -> Number: ...")
    lines.append("    def __rsub__(self, other: object) -> Number: ...")
    lines.append("    def __pow__(self, exp: object) -> Number: ...")
    lines.append("    def __neg__(self) -> Number: ...")
    lines.append("    def __pos__(self) -> Number: ...")
    lines.append("    def __repr__(self) -> str: ...")
    lines.append("")
    return lines


def generate_constant_instances() -> list[str]:
    """Generate stubs for all constant instances."""
    lines = []
    lines.append("# Constant instances loaded from comprehensive.ucon.toml")

    constants = _get_constants()
    for name in sorted(constants.keys()):
        lines.append(f"{name}: Constant")

    lines.append("")
    return lines


def generate_aliases() -> list[str]:
    """Generate stubs for alias names from __all__."""
    lines = []
    lines.append("# Aliases accessible via module-level __getattr__")

    constants = _get_constants()
    # Aliases are names in __all__ that are NOT descriptive constant names
    # and are not 'Constant', 'all_constants', 'get_constant_by_symbol'
    skip = {'Constant', 'all_constants', 'get_constant_by_symbol'}
    already = set(constants.keys())
    for name in CONST_ALL:
        if name in skip or name in already:
            continue
        lines.append(f"{name}: Constant")

    lines.append("")
    return lines


def generate_functions() -> list[str]:
    """Generate stubs for public functions."""
    lines = []
    lines.append("# Public API")
    lines.append("def all_constants() -> list[Constant]: ...")
    lines.append("def get_constant_by_symbol(symbol: str) -> Constant | None: ...")
    lines.append("")
    return lines


def generate() -> str:
    """Generate the complete stub file."""
    lines = [HEADER]
    lines.extend(generate_constant_class())
    lines.extend(generate_constant_instances())
    lines.extend(generate_aliases())
    lines.extend(generate_functions())
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate constants.pyi stubs")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if existing stub matches generated (exit 1 if different)",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=None,
        help="Output file (default: stdout)",
    )
    args = parser.parse_args()

    generated = generate()

    if args.check:
        stub_path = Path(__file__).parent.parent / "ucon" / "constants.pyi"
        if not stub_path.exists():
            print(f"ERROR: {stub_path} does not exist", file=sys.stderr)
            sys.exit(1)

        existing = stub_path.read_text()
        if existing.strip() != generated.strip():
            print("ERROR: constants.pyi is out of date. Run 'make stubs' to regenerate.", file=sys.stderr)
            sys.exit(1)

        print("OK: constants.pyi is up to date")
        sys.exit(0)

    if args.output:
        args.output.write_text(generated)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(generated)


if __name__ == "__main__":
    main()
