#!/usr/bin/env python3
"""
Generate type stubs for ucon.units from runtime introspection.

This script imports ucon.units and generates a .pyi stub file by:
1. Extracting all Unit objects loaded from the TOML
2. Including UnitSystem instances (si, imperial)
3. Including the sentinel ``none`` unit
4. Including backward-compat aliases (pint_volume, point_typo)
5. Including the ``have()`` function

Usage:
    python scripts/generate_unit_stubs.py > ucon/units.pyi
    python scripts/generate_unit_stubs.py --check  # Verify stub is current
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure we import from the local package
sys.path.insert(0, str(Path(__file__).parent.parent))

from ucon.core import Unit, UnitSystem
import ucon.units as units_module
from ucon._loader import get_units


HEADER = '''\
# Auto-generated type stubs for ucon.units
# Generated by: scripts/generate_unit_stubs.py
# Regenerate with: make stubs
# DO NOT EDIT MANUALLY

from ucon.core import BaseForm, Dimension, Scale, Unit, UnitSystem, UnknownUnitError
from ucon.dimension import (
    NONE, TIME, LENGTH, MASS, CURRENT, TEMPERATURE,
    LUMINOUS_INTENSITY, AMOUNT_OF_SUBSTANCE, INFORMATION,
    ANGLE, SOLID_ANGLE, RATIO, COUNT,
    VELOCITY, ACCELERATION, FORCE, ENERGY, POWER,
    MOMENTUM, ANGULAR_MOMENTUM, AREA, VOLUME, DENSITY, PRESSURE, FREQUENCY,
    DYNAMIC_VISCOSITY, KINEMATIC_VISCOSITY, LINEAR_DENSITY, GRAVITATION,
    CHARGE, VOLTAGE, RESISTANCE, RESISTIVITY, CONDUCTANCE, CONDUCTIVITY,
    CAPACITANCE, INDUCTANCE, MAGNETIC_FLUX, MAGNETIC_FLUX_DENSITY,
    MAGNETIC_PERMEABILITY, PERMITTIVITY, ELECTRIC_FIELD_STRENGTH,
    MAGNETIC_FIELD_STRENGTH,
    ENTROPY, SPECIFIC_HEAT_CAPACITY, THERMAL_CONDUCTIVITY,
    ILLUMINANCE, CATALYTIC_ACTIVITY, MOLAR_MASS, MOLAR_VOLUME, CONCENTRATION,
    WAVENUMBER, RADIANT_EXPOSURE, EXPOSURE, ELECTRIC_DIPOLE_MOMENT,
    CGS_FORCE, CGS_ENERGY, CGS_PRESSURE,
    CGS_DYNAMIC_VISCOSITY, CGS_KINEMATIC_VISCOSITY,
    CGS_ACCELERATION, CGS_WAVENUMBER, CGS_RADIANT_EXPOSURE,
    CGS_ESU_CHARGE, CGS_ESU_CURRENT, CGS_ESU_VOLTAGE,
    CGS_ESU_RESISTANCE, CGS_ESU_CAPACITANCE,
    CGS_ESU_MAGNETIC_FLUX_DENSITY, CGS_ESU_MAGNETIC_FLUX,
    CGS_ESU_MAGNETIC_FIELD_STRENGTH, CGS_ESU_ELECTRIC_DIPOLE_MOMENT,
    CGS_EMU_CURRENT, CGS_EMU_CHARGE, CGS_EMU_VOLTAGE,
    CGS_EMU_RESISTANCE, CGS_EMU_CAPACITANCE, CGS_EMU_INDUCTANCE,
    NATURAL_ENERGY,
    PLANCK_ENERGY, PLANCK_LENGTH,
    ATOMIC_ENERGY, ATOMIC_LENGTH,
)
from ucon.resolver import register_unit, register_priority_scaled_alias, get_unit_by_name

'''


def generate_unit_stubs() -> list[str]:
    """Generate stubs for all units loaded from TOML."""
    lines = []
    lines.append("# Unit instances loaded from comprehensive.ucon.toml")

    units = get_units()
    for name in sorted(units.keys()):
        if name and name.isidentifier():
            lines.append(f"{name}: Unit")

    lines.append("")
    return lines


def generate_special_stubs() -> list[str]:
    """Generate stubs for sentinel, aliases, systems, and functions."""
    lines = []

    lines.append("# Sentinel unit")
    lines.append("none: Unit")
    lines.append("")

    lines.append("# Backward-compat variable aliases")
    lines.append("pint_volume: Unit")
    lines.append("point_typo: Unit")
    lines.append("")

    lines.append("# Predefined unit systems")
    lines.append("si: UnitSystem")
    lines.append("imperial: UnitSystem")
    lines.append("")

    lines.append("# Public API")
    lines.append("def have(name: str) -> bool: ...")
    lines.append("")

    return lines


def generate() -> str:
    """Generate the complete stub file."""
    lines = [HEADER]
    lines.extend(generate_unit_stubs())
    lines.extend(generate_special_stubs())
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate units.pyi stubs")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if existing stub matches generated (exit 1 if different)",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=None,
        help="Output file (default: stdout)",
    )
    args = parser.parse_args()

    generated = generate()

    if args.check:
        stub_path = Path(__file__).parent.parent / "ucon" / "units.pyi"
        if not stub_path.exists():
            print(f"ERROR: {stub_path} does not exist", file=sys.stderr)
            sys.exit(1)

        existing = stub_path.read_text()
        if existing.strip() != generated.strip():
            print("ERROR: units.pyi is out of date. Run 'make stubs' to regenerate.", file=sys.stderr)
            sys.exit(1)

        print("OK: units.pyi is up to date")
        sys.exit(0)

    if args.output:
        args.output.write_text(generated)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(generated)


if __name__ == "__main__":
    main()
