# Auto-generated type stubs for ucon.constants
# Generated by: scripts/generate_constant_stubs.py
# Regenerate with: make stubs
# DO NOT EDIT MANUALLY

from typing import Union

from ucon.core import Number, Unit, UnitProduct
from ucon.dimension import Dimension


class Constant:
    """A physical constant with CODATA uncertainty."""

    symbol: str
    name: str
    value: float
    unit: Union[Unit, UnitProduct]
    uncertainty: Union[float, None]
    source: str = "CODATA 2022"
    category: str = "measured"
    aliases: tuple = ()

    def as_number(self) -> Number: ...

    @property
    def dimension(self) -> Dimension: ...
    @property
    def is_exact(self) -> bool: ...

    def __mul__(self, other: object) -> Number: ...
    def __rmul__(self, other: object) -> Number: ...
    def __truediv__(self, other: object) -> Number: ...
    def __rtruediv__(self, other: object) -> Number: ...
    def __add__(self, other: object) -> Number: ...
    def __radd__(self, other: object) -> Number: ...
    def __sub__(self, other: object) -> Number: ...
    def __rsub__(self, other: object) -> Number: ...
    def __pow__(self, exp: object) -> Number: ...
    def __neg__(self) -> Number: ...
    def __pos__(self) -> Number: ...
    def __repr__(self) -> str: ...

# Constant instances loaded from comprehensive.ucon.toml
atomic_unit_of_time: Constant
avogadro_constant: Constant
bohr_radius: Constant
boltzmann_constant: Constant
electron_mass: Constant
elementary_charge: Constant
fine_structure_constant: Constant
gravitational_constant: Constant
hartree_energy: Constant
hyperfine_transition_frequency: Constant
luminous_efficacy: Constant
molar_gas_constant: Constant
neutron_mass: Constant
planck_constant: Constant
planck_length: Constant
planck_mass: Constant
planck_temperature: Constant
planck_time: Constant
proton_mass: Constant
reduced_planck_constant: Constant
rydberg_energy: Constant
speed_of_light: Constant
standard_gravity: Constant
stefan_boltzmann_constant: Constant
vacuum_permeability: Constant
vacuum_permittivity: Constant

# Aliases accessible via module-level __getattr__
c: Constant
h: Constant
ℏ: Constant
e: Constant
k_B: Constant
N_A: Constant
G: Constant
α: Constant
ε₀: Constant
μ₀: Constant
mₑ: Constant
mₚ: Constant
mₙ: Constant
σ: Constant
R: Constant
gₙ: Constant
Eₕ: Constant
a₀: Constant
hbar: Constant
alpha: Constant
epsilon_0: Constant
mu_0: Constant
m_e: Constant
m_p: Constant
m_n: Constant
g_n: Constant
g_0: Constant
E_h: Constant
a_0: Constant
m_P: Constant
l_P: Constant
t_P: Constant
T_P: Constant

# Public API
def all_constants() -> list[Constant]: ...
def get_constant_by_symbol(symbol: str) -> Constant | None: ...
