# Auto-generated type stubs for ucon.units
# Generated by: scripts/generate_unit_stubs.py
# Regenerate with: make stubs
# DO NOT EDIT MANUALLY

from ucon.core import BaseForm, Dimension, Scale, Unit, UnitSystem, UnknownUnitError
from ucon.dimension import (
    NONE, TIME, LENGTH, MASS, CURRENT, TEMPERATURE,
    LUMINOUS_INTENSITY, AMOUNT_OF_SUBSTANCE, INFORMATION,
    ANGLE, SOLID_ANGLE, RATIO, COUNT,
    VELOCITY, ACCELERATION, FORCE, ENERGY, POWER,
    MOMENTUM, ANGULAR_MOMENTUM, AREA, VOLUME, DENSITY, PRESSURE, FREQUENCY,
    DYNAMIC_VISCOSITY, KINEMATIC_VISCOSITY, LINEAR_DENSITY, GRAVITATION,
    CHARGE, VOLTAGE, RESISTANCE, RESISTIVITY, CONDUCTANCE, CONDUCTIVITY,
    CAPACITANCE, INDUCTANCE, MAGNETIC_FLUX, MAGNETIC_FLUX_DENSITY,
    MAGNETIC_PERMEABILITY, PERMITTIVITY, ELECTRIC_FIELD_STRENGTH,
    MAGNETIC_FIELD_STRENGTH,
    ENTROPY, SPECIFIC_HEAT_CAPACITY, THERMAL_CONDUCTIVITY,
    ILLUMINANCE, CATALYTIC_ACTIVITY, MOLAR_MASS, MOLAR_VOLUME, CONCENTRATION,
    WAVENUMBER, RADIANT_EXPOSURE, EXPOSURE, ELECTRIC_DIPOLE_MOMENT,
    CGS_FORCE, CGS_ENERGY, CGS_PRESSURE,
    CGS_DYNAMIC_VISCOSITY, CGS_KINEMATIC_VISCOSITY,
    CGS_ACCELERATION, CGS_WAVENUMBER, CGS_RADIANT_EXPOSURE,
    CGS_ESU_CHARGE, CGS_ESU_CURRENT, CGS_ESU_VOLTAGE,
    CGS_ESU_RESISTANCE, CGS_ESU_CAPACITANCE,
    CGS_ESU_MAGNETIC_FLUX_DENSITY, CGS_ESU_MAGNETIC_FLUX,
    CGS_ESU_MAGNETIC_FIELD_STRENGTH, CGS_ESU_ELECTRIC_DIPOLE_MOMENT,
    CGS_EMU_CURRENT, CGS_EMU_CHARGE, CGS_EMU_VOLTAGE,
    CGS_EMU_RESISTANCE, CGS_EMU_CAPACITANCE, CGS_EMU_INDUCTANCE,
    NATURAL_ENERGY,
    PLANCK_ENERGY, PLANCK_LENGTH,
    ATOMIC_ENERGY, ATOMIC_LENGTH,
)
from ucon.resolver import register_unit, register_priority_scaled_alias, get_unit_by_name


# Unit instances loaded from comprehensive.ucon.toml
abcoulomb: Unit
abfarad: Unit
abhenry: Unit
abohm: Unit
abvolt: Unit
acre: Unit
acre_foot: Unit
ampere: Unit
ampere_hour: Unit
ampere_per_meter: Unit
angstrom: Unit
apostilb: Unit
arcminute: Unit
arcsecond: Unit
astronomical_unit: Unit
atmosphere: Unit
atomic_time: Unit
bar: Unit
barn: Unit
barrel: Unit
barye: Unit
basis_point: Unit
becquerel: Unit
bel: Unit
biot: Unit
bit: Unit
bohr_radius: Unit
boiler_horsepower: Unit
btu: Unit
bushel: Unit
byte: Unit
cable: Unit
calorie: Unit
candela: Unit
carat: Unit
celsius: Unit
centimeter_mercury: Unit
centimeter_water: Unit
chain: Unit
coulomb: Unit
coulomb_meter: Unit
coulomb_per_kilogram: Unit
cubic_foot: Unit
cubic_inch: Unit
cubic_yard: Unit
cup: Unit
curie: Unit
dalton: Unit
day: Unit
debye: Unit
decibel: Unit
decibel_milliwatt: Unit
decibel_spl: Unit
decibel_volt: Unit
decibel_watt: Unit
degree: Unit
denier: Unit
dram: Unit
dyne: Unit
each: Unit
electrical_horsepower: Unit
electron_mass: Unit
electron_volt: Unit
enzyme_unit: Unit
erg: Unit
fahrenheit: Unit
farad: Unit
fathom: Unit
fluid_ounce: Unit
foot: Unit
foot_candle: Unit
foot_pound: Unit
fortnight: Unit
fraction: Unit
furlong: Unit
galileo: Unit
gallon: Unit
gauss: Unit
gilbert: Unit
gill: Unit
gradian: Unit
grain: Unit
gram: Unit
gram_force: Unit
gray: Unit
hand: Unit
hartree: Unit
hectare: Unit
henry: Unit
hertz: Unit
horsepower: Unit
hour: Unit
imperial_cup: Unit
imperial_fluid_ounce: Unit
imperial_gallon: Unit
imperial_gill: Unit
imperial_pint: Unit
imperial_quart: Unit
inch: Unit
inch_mercury: Unit
inch_water: Unit
international_ampere: Unit
international_ohm: Unit
international_volt: Unit
jansky: Unit
joule: Unit
joule_per_kelvin: Unit
joule_per_square_meter: Unit
katal: Unit
kayser: Unit
kelvin: Unit
kilogram: Unit
kilogram_force: Unit
kip: Unit
knot: Unit
ksi: Unit
lambert: Unit
langley: Unit
league: Unit
light_year: Unit
liter: Unit
long_ton: Unit
lumen: Unit
lux: Unit
maxwell: Unit
meter: Unit
meter_per_second_squared: Unit
metric_horsepower: Unit
metric_ton: Unit
metric_ton_force: Unit
mil: Unit
mile: Unit
mile_per_hour: Unit
millimeter_mercury: Unit
millimeter_water: Unit
minim: Unit
minute: Unit
molar: Unit
mole: Unit
month: Unit
nautical_mile: Unit
neper: Unit
newton: Unit
nines: Unit
nit: Unit
oersted: Unit
ohm: Unit
ounce: Unit
ounce_force: Unit
pH: Unit
parsec: Unit
pascal: Unit
pascal_second: Unit
peck: Unit
pennyweight: Unit
percent: Unit
permille: Unit
phot: Unit
pica: Unit
pint: Unit
planck_energy: Unit
planck_length: Unit
planck_mass: Unit
planck_temperature: Unit
planck_time: Unit
point: Unit
poise: Unit
pound: Unit
pound_force: Unit
poundal: Unit
ppb: Unit
ppm: Unit
psi: Unit
quart: Unit
rad_dose: Unit
radian: Unit
rankine: Unit
reaumur: Unit
reciprocal_meter: Unit
refrigeration_ton: Unit
rem: Unit
reyn: Unit
rod: Unit
roentgen: Unit
rydberg: Unit
second: Unit
shake: Unit
short_ton: Unit
siemens: Unit
sievert: Unit
slug: Unit
square_degree: Unit
square_meter_per_second: Unit
standard_gravity: Unit
statampere: Unit
statcoulomb: Unit
statfarad: Unit
statohm: Unit
statvolt: Unit
steradian: Unit
stere: Unit
stilb: Unit
stokes: Unit
stone: Unit
tablespoon: Unit
teaspoon: Unit
technical_atmosphere: Unit
tesla: Unit
tex: Unit
therm: Unit
thermochemical_calorie: Unit
ton_force: Unit
ton_tnt: Unit
tonne_oil_equivalent: Unit
torr: Unit
troy_ounce: Unit
turn: Unit
volt: Unit
volt_ampere: Unit
watt: Unit
watt_hour: Unit
weber: Unit
webers_per_meter: Unit
week: Unit
yard: Unit
year: Unit

# Sentinel unit
none: Unit

# Backward-compat variable aliases
pint_volume: Unit
point_typo: Unit

# Predefined unit systems
si: UnitSystem
imperial: UnitSystem

# Public API
def have(name: str) -> bool: ...
