name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Make virtual environment
        run: make

      - name: Run all tests
        run: make tests
