name: tests

on: [push]

jobs:
  check:
    if: startsWith(github.ref, 'refs/tags') != true
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make virtual environment
        run: make

      - name: Run all tests
        run: make tests

