name: tests_trigger

on:
  push:
    branches: [main]     # any branch push
    tags: ['*']          # any tag push
  pull_request:
    branches: ['**']     # run for all PRs and pushes to open PRs

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.diff.outputs.code_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        run: |
          git fetch origin main --depth=1 || true
          if git diff --quiet origin/main -- ucon/ tests/ noxfile.py setup.py requirements*.txt; then
            echo "::notice::No relevant code changes detected."
            echo "code_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::Code changes detected."
            echo "code_changed=true" >> "$GITHUB_OUTPUT"
          fi

  run_tests:
    if: needs.detect_changes.outputs.code_changed == 'true'
    needs: detect_changes
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
